// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function LocalServerURL() {
  return window['go']['main']['App']['LocalServerURL']();
}
